id: IF443BD40
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T16:29:32+00:00'
last_modified: '2022-06-10T08:54:29.471086+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74475
  title: སྐུ་འབུམ་གདན་རབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AA4D:
      image_group_id: I2PD18102
      title: Volume 1 of dpe war mchog sprul 'jam dbyangs bsod nams dbang po'i gsan
        yig 'dod rgu'i bang mdzod/
      total_pages: 594
      order: 1
      base_file: AA4D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
